INSERT INTO `departments` (`id`, `name`)
VALUES
    (1, 'Antioquia'),
    (2, 'Atlantico'),
    (3, 'D. C. Santa Fe De Bogotá'),
    (4, 'Bolivar'),
    (5, 'Boyaca'),
    (6, 'Caldas'),
    (7, 'Caqueta'),
    (8, 'Cauca'),
    (9, 'Cesar'),
    (10, 'Cordoba'),
    (11, 'Cundinamarca'),
    (12, 'Choco'),
    (13, 'Huila'),
    (14, 'La Guajira'),
    (15, 'Magdalena'),
    (16, 'Meta'),
    (17, 'Nariño'),
    (18, 'Norte De Santander'),
    (19, 'Quindio'),
    (20, 'Risaralda'),
    (21, 'Santander'),
    (22, 'Sucre'),
    (23, 'Tolima'),
    (24, 'Valle'),
    (25, 'Arauca'),
    (26, 'Casanare'),
    (27, 'Putumayo'),
    (28, 'San Andres'),
    (29, 'Amazonas'),
    (30, 'Guainia'),
    (31, 'Guaviare'),
    (32, 'Vaupes'),
    (33, 'Vichada');

INSERT INTO `cities` (`department_id`, `name`)
VALUES
	(1, 'Medellin'),
	(1, 'Abejorral'),
	(1, 'Abriaqui'),
	(1, 'Alejandria'),
	(1, 'Amaga'),
	(1, 'Amalfi'),
	(1, 'Andes'),
	(1, 'Angelopolis'),
	(1, 'Angostura'),
	(1, 'Anori'),
	(1, 'Antioquia'),
	(1, 'Anza'),
	(1, 'Apartado'),
	(1, 'Arboletes'),
	(1, 'Argelia'),
	(1, 'Armenia'),
	(1, 'Barbosa'),
	(1, 'Belmira'),
	(1, 'Bello'),
	(1, 'Betania'),
	(1, 'Betulia'),
	(1, 'Bolivar'),
	(1, 'Briceño'),
	(1, 'Buritica'),
	(1, 'Caceres'),
	(1, 'Caicedo'),
	(1, 'Caldas'),
	(1, 'Campamento'),
	(1, 'Cañasgordas'),
	(1, 'Caracoli'),
	(1, 'Caramanta'),
	(1, 'Carepa'),
	(1, 'Carmen De Viboral'),
	(1, 'Carolina'),
	(1, 'Caucasia'),
	(1, 'Chigorodo'),
	(1, 'Cisneros'),
	(1, 'Cocorna'),
	(1, 'Concepcion'),
	(1, 'Concordia'),
	(1, 'Copacabana'),
	(1, 'Dabeiba'),
	(1, 'Don Matias'),
	(1, 'Ebejico'),
	(1, 'El Bagre'),
	(1, 'Entrerrios'),
	(1, 'Envigado'),
	(1, 'Fredonia'),
	(1, 'Frontino'),
	(1, 'Giraldo'),
	(1, 'Girardota'),
	(1, 'Gomez Plata'),
	(1, 'Granada'),
	(1, 'Guadalupe'),
	(1, 'Guarne'),
	(1, 'Guatape'),
	(1, 'Heliconia'),
	(1, 'Hispania'),
	(1, 'Itagui'),
	(1, 'Ituango'),
	(1, 'Jardin'),
	(1, 'Jerico'),
	(1, 'La Ceja'),
	(1, 'La Estrella'),
	(1, 'La Pintada'),
	(1, 'La Union'),
	(1, 'Liborina'),
	(1, 'Maceo'),
	(1, 'Marinilla'),
	(1, 'Montebello'),
	(1, 'Murindo'),
	(1, 'Mutata'),
	(1, 'Nariño'),
	(1, 'Necocli'),
	(1, 'Nechi'),
	(1, 'Olaya'),
	(1, 'Peñol'),
	(1, 'Peque'),
	(1, 'Pueblorrico'),
	(1, 'Puerto Berrio'),
	(1, 'Puerto Nare (La Magdalena)'),
	(1, 'Puerto Triunfo'),
	(1, 'Remedios'),
	(1, 'Retiro'),
	(1, 'Rionegro'),
	(1, 'Sabanalarga'),
	(1, 'Sabaneta'),
	(1, 'Salgar'),
	(1, 'San Andres'),
	(1, 'San Carlos'),
	(1, 'San Francisco'),
	(1, 'San Jeronimo'),
	(1, 'San Jose De La Montaña'),
	(1, 'San Juan De Uraba'),
	(1, 'San Luis'),
	(1, 'San Pedro'),
	(1, 'San Pedro De Uraba'),
	(1, 'San Rafael'),
	(1, 'San Roque'),
	(1, 'San Vicente'),
	(1, 'Santa Barbara'),
	(1, 'Santa Rosa De Osos'),
	(1, 'Santo Domingo'),
	(1, 'Santuario'),
	(1, 'Segovia'),
	(1, 'Sonson'),
	(1, 'Sopetran'),
	(1, 'Tamesis'),
	(1, 'Taraza'),
	(1, 'Tarso'),
	(1, 'Titiribi'),
	(1, 'Toledo'),
	(1, 'Turbo'),
	(1, 'Uramita'),
	(1, 'Urrao'),
	(1, 'Valdivia'),
	(1, 'Valparaiso'),
	(1, 'Vegachi'),
	(1, 'Venecia'),
	(1, 'Vigia Del Fuerte'),
	(1, 'Yali'),
	(1, 'Yarumal'),
	(1, 'Yolombo'),
	(1, 'Yondo'),
	(1, 'Zaragoza'),
	(2, 'Barranquilla (Distrito Especial Industrial Y Portuario De Barranquilla)'),
	(2, 'Baranoa'),
	(2, 'Campo De La Cruz'),
	(2, 'Candelaria'),
	(2, 'Galapa'),
	(2, 'Juan De Acosta'),
	(2, 'Luruaco'),
	(2, 'Malambo'),
	(2, 'Manati'),
	(2, 'Palmar De Varela'),
	(2, 'Piojo'),
	(2, 'Polo Nuevo'),
	(2, 'Ponedera'),
	(2, 'Puerto Colombia'),
	(2, 'Repelon'),
	(2, 'Sabanagrande'),
	(2, 'Sabanalarga'),
	(2, 'Santa Lucia'),
	(2, 'Santo Tomas'),
	(2, 'Soledad'),
	(2, 'Suan'),
	(2, 'Tubara'),
	(2, 'Usiacuri'),
	(3, 'Santa Fe De Bogotá'),
	(3, 'Usaquen'),
	(3, 'Chapinero'),
	(3, 'Santa Fe'),
	(3, 'San Cristobal'),
	(3, 'Usme'),
	(3, 'Tunjuelito'),
	(3, 'Bosa'),
	(3, 'Kennedy'),
	(3, 'Fontibon'),
	(3, 'Engativa'),
	(3, 'Suba'),
	(3, 'Barrios Unidos'),
	(3, 'Teusaquillo'),
	(3, 'Martires'),
	(3, 'Antonio Nariño'),
	(3, 'Puente Aranda'),
	(3, 'Candelaria'),
	(3, 'Rafael Uribe'),
	(3, 'Ciudad Bolivar'),
	(3, 'Sumapaz'),
	(4, 'Cartagena (Distrito Turistico Y Cultural De Cartagena)'),
	(4, 'Achi'),
	(4, 'Altos Del Rosario'),
	(4, 'Arenal'),
	(4, 'Arjona'),
	(4, 'Arroyohondo'),
	(4, 'Barranco De Loba'),
	(4, 'Calamar'),
	(4, 'Cantagallo'),
	(4, 'Cicuco'),
	(4, 'Cordoba'),
	(4, 'Clemencia'),
	(4, 'El Carmen De Bolivar'),
	(4, 'El Guamo'),
	(4, 'El Peñon'),
	(4, 'Hatillo De Loba'),
	(4, 'Magangue'),
	(4, 'Mahates'),
	(4, 'Margarita'),
	(4, 'Maria La Baja'),
	(4, 'Montecristo'),
	(4, 'Mompos'),
	(4, 'Morales'),
	(4, 'Pinillos'),
	(4, 'Regidor'),
	(4, 'Rio Viejo'),
	(4, 'San Cristobal'),
	(4, 'San Estanislao'),
	(4, 'San Fernando'),
	(4, 'San Jacinto'),
	(4, 'San Jacinto Del Cauca'),
	(4, 'San Juan Nepomuceno'),
	(4, 'San Martin De Loba'),
	(4, 'San Pablo'),
	(4, 'Santa Catalina'),
	(4, 'Santa Rosa'),
	(4, 'Santa Rosa Del Sur'),
	(4, 'Simiti'),
	(4, 'Soplaviento'),
	(4, 'Talaigua Nuevo'),
	(4, 'Tiquisio (Puerto Rico)'),
	(4, 'Turbaco'),
	(4, 'Turbana'),
	(4, 'Villanueva'),
	(4, 'Zambrano'),
	(5, 'Tunja'),
	(5, 'Almeida'),
	(5, 'Aquitania'),
	(5, 'Arcabuco'),
	(5, 'Belen'),
	(5, 'Berbeo'),
	(5, 'Beteitiva'),
	(5, 'Boavita'),
	(5, 'Boyaca'),
	(5, 'Briceño'),
	(5, 'Buenavista'),
	(5, 'Busbanza'),
	(5, 'Caldas'),
	(5, 'Campohermoso'),
	(5, 'Cerinza'),
	(5, 'Chinavita'),
	(5, 'Chiquinquira'),
	(5, 'Chiscas'),
	(5, 'Chita'),
	(5, 'Chitaraque'),
	(5, 'Chivata'),
	(5, 'Cienega'),
	(5, 'Combita'),
	(5, 'Coper'),
	(5, 'Corrales'),
	(5, 'Covarachia'),
	(5, 'Cubara'),
	(5, 'Cucaita'),
	(5, 'Cuitiva'),
	(5, 'Chiquiza'),
	(5, 'Chivor'),
	(5, 'Duitama'),
	(5, 'El Cocuy'),
	(5, 'El Espino'),
	(5, 'Firavitoba'),
	(5, 'Floresta'),
	(5, 'Gachantiva'),
	(5, 'Gameza'),
	(5, 'Garagoa'),
	(5, 'Guacamayas'),
	(5, 'Guateque'),
	(5, 'Guayata'),
	(5, 'Guican'),
	(5, 'Iza'),
	(5, 'Jenesano'),
	(5, 'Jerico'),
	(5, 'Labranzagrande'),
	(5, 'La Capilla'),
	(5, 'La Victoria'),
	(5, 'La Uvita'),
	(5, 'Villa De Leiva'),
	(5, 'Macanal'),
	(5, 'Maripi'),
	(5, 'Miraflores'),
	(5, 'Mongua'),
	(5, 'Mongui'),
	(5, 'Moniquira'),
	(5, 'Motavita'),
	(5, 'Muzo'),
	(5, 'Nobsa'),
	(5, 'Nuevo Colon'),
	(5, 'Oicata'),
	(5, 'Otanche'),
	(5, 'Pachavita'),
	(5, 'Paez'),
	(5, 'Paipa'),
	(5, 'Pajarito'),
	(5, 'Panqueba'),
	(5, 'Pauna'),
	(5, 'Paya'),
	(5, 'Paz Del Rio'),
	(5, 'Pesca'),
	(5, 'Pisba'),
	(5, 'Puerto Boyaca'),
	(5, 'Quipama'),
	(5, 'Ramiriqui'),
	(5, 'Raquira'),
	(5, 'Rondon'),
	(5, 'Saboya'),
	(5, 'Sachica'),
	(5, 'Samaca'),
	(5, 'San Eduardo'),
	(5, 'San Jose De Pare'),
	(5, 'San Luis De Gaceno'),
	(5, 'San Mateo'),
	(5, 'San Miguel De Sema'),
	(5, 'San Pablo De Borbur'),
	(5, 'Santana'),
	(5, 'Santa Maria'),
	(5, 'Santa Rosa De Viterbo'),
	(5, 'Santa Sofia'),
	(5, 'Sativanorte'),
	(5, 'Sativasur'),
	(5, 'Siachoque'),
	(5, 'Soata'),
	(5, 'Socota'),
	(5, 'Socha'),
	(5, 'Sogamoso'),
	(5, 'Somondoco'),
	(5, 'Sora'),
	(5, 'Sotaquira'),
	(5, 'Soraca'),
	(5, 'Susacon'),
	(5, 'Sutamarchan'),
	(5, 'Sutatenza'),
	(5, 'Tasco'),
	(5, 'Tenza'),
	(5, 'Tibana'),
	(5, 'Tibasosa'),
	(5, 'Tinjaca'),
	(5, 'Tipacoque'),
	(5, 'Toca'),
	(5, 'Togui'),
	(5, 'Topaga'),
	(5, 'Tota'),
	(5, 'Tunungua'),
	(5, 'Turmeque'),
	(5, 'Tuta'),
	(5, 'Tutasa'),
	(5, 'Umbita'),
	(5, 'Ventaquemada'),
	(5, 'Viracacha'),
	(5, 'Zetaquira'),
	(6, 'Manizales'),
	(6, 'Aguadas'),
	(6, 'Anserma'),
	(6, 'Aranzazu'),
	(6, 'Belalcazar'),
	(6, 'Chinchina'),
	(6, 'Filadelfia'),
	(6, 'La Dorada'),
	(6, 'La Merced'),
	(6, 'Manzanares'),
	(6, 'Marmato'),
	(6, 'Marquetalia'),
	(6, 'Marulanda'),
	(6, 'Neira'),
	(6, 'Norcasia'),
	(6, 'Pacora'),
	(6, 'Palestina'),
	(6, 'Pensilvania'),
	(6, 'Riosucio'),
	(6, 'Risaralda'),
	(6, 'Salamina'),
	(6, 'Samana'),
	(6, 'San Jose'),
	(6, 'Supia'),
	(6, 'Victoria'),
	(6, 'Villamaria'),
	(6, 'Viterbo'),
	(7, 'Florencia'),
	(7, 'Albania'),
	(7, 'Belen De Los Andaquies'),
	(7, 'Cartagena Del Chaira'),
	(7, 'Curillo'),
	(7, 'El Doncello'),
	(7, 'El Paujil'),
	(7, 'La Montañita'),
	(7, 'Milan'),
	(7, 'Morelia'),
	(7, 'Puerto Rico'),
	(7, 'San Jose De Fragua'),
	(7, 'San Vicente Del Caguan'),
	(7, 'Solano'),
	(7, 'Solita'),
	(7, 'Valparaiso'),
	(8, 'Popayan'),
	(8, 'Almaguer'),
	(8, 'Argelia'),
	(8, 'Balboa'),
	(8, 'Bolivar'),
	(8, 'Buenos Aires'),
	(8, 'Cajibio'),
	(8, 'Caldono'),
	(8, 'Caloto'),
	(8, 'Corinto'),
	(8, 'El Tambo'),
	(8, 'Florencia'),
	(8, 'Guapi'),
	(8, 'Inza'),
	(8, 'Jambalo'),
	(8, 'La Sierra'),
	(8, 'La Vega'),
	(8, 'Lopez (Micay)'),
	(8, 'Mercaderes'),
	(8, 'Miranda'),
	(8, 'Morales'),
	(8, 'Padilla'),
	(8, 'Paez (Belalcazar)'),
	(8, 'Patia (El Bordo)'),
	(8, 'Piamonte'),
	(8, 'Piendamo'),
	(8, 'Puerto Tejada'),
	(8, 'Purace (Coconuco)'),
	(8, 'Rosas'),
	(8, 'San Sebastian'),
	(8, 'Santander De Quilichao'),
	(8, 'Santa Rosa'),
	(8, 'Silvia'),
	(8, 'Sotara (Paispamba)'),
	(8, 'Suarez'),
	(8, 'Timbio'),
	(8, 'Timbiqui'),
	(8, 'Toribio'),
	(8, 'Totoro'),
	(8, 'Villarica'),
	(9, 'Valledupar'),
	(9, 'Aguachica'),
	(9, 'Agustin Codazzi'),
	(9, 'Astrea'),
	(9, 'Becerril'),
	(9, 'Bosconia'),
	(9, 'Chimichagua'),
	(9, 'Chiriguana'),
	(9, 'Curumani'),
	(9, 'El Copey'),
	(9, 'El Paso'),
	(9, 'Gamarra'),
	(9, 'Gonzalez'),
	(9, 'La Gloria'),
	(9, 'La Jagua Ibirico'),
	(9, 'Manaure (Balcon Del Cesar)'),
	(9, 'Pailitas'),
	(9, 'Pelaya'),
	(9, 'Pueblo Bello'),
	(9, 'Rio De Oro'),
	(9, 'La Paz (Robles)'),
	(9, 'San Alberto'),
	(9, 'San Diego'),
	(9, 'San Martin'),
	(9, 'Tamalameque'),
	(10, 'Monteria'),
	(10, 'Ayapel'),
	(10, 'Buenavista'),
	(10, 'Canalete'),
	(10, 'Cerete'),
	(10, 'Chima'),
	(10, 'Chinu'),
	(10, 'Cienaga De Oro'),
	(10, 'Cotorra'),
	(10, 'La Apartada'),
	(10, 'Lorica'),
	(10, 'Los Cordobas'),
	(10, 'Momil'),
	(10, 'Montelibano'),
	(10, 'Moñitos'),
	(10, 'Planeta Rica'),
	(10, 'Pueblo Nuevo'),
	(10, 'Puerto Escondido'),
	(10, 'Puerto Libertador'),
	(10, 'Purisima'),
	(10, 'Sahagun'),
	(10, 'San Andres Sotavento'),
	(10, 'San Antero'),
	(10, 'San Bernardo Del Viento'),
	(10, 'San Carlos'),
	(10, 'San Pelayo'),
	(10, 'Tierralta'),
	(10, 'Valencia'),
	(11, 'Agua De Dios'),
	(11, 'Alban'),
	(11, 'Anapoima'),
	(11, 'Anolaima'),
	(11, 'Arbelaez'),
	(11, 'Beltran'),
	(11, 'Bituima'),
	(11, 'Bojaca'),
	(11, 'Cabrera'),
	(11, 'Cachipay'),
	(11, 'Cajica'),
	(11, 'Caparrapi'),
	(11, 'Caqueza'),
	(11, 'Carmen De Carupa'),
	(11, 'Chaguani'),
	(11, 'Chia'),
	(11, 'Chipaque'),
	(11, 'Choachi'),
	(11, 'Choconta'),
	(11, 'Cogua'),
	(11, 'Cota'),
	(11, 'Cucunuba'),
	(11, 'El Colegio'),
	(11, 'El Peñon'),
	(11, 'El Rosal'),
	(11, 'Facatativa'),
	(11, 'Fomeque'),
	(11, 'Fosca'),
	(11, 'Funza'),
	(11, 'Fuquene'),
	(11, 'Fusagasuga'),
	(11, 'Gachala'),
	(11, 'Gachancipa'),
	(11, 'Gacheta'),
	(11, 'Gama'),
	(11, 'Girardot'),
	(11, 'Granada'),
	(11, 'Guacheta'),
	(11, 'Guaduas'),
	(11, 'Guasca'),
	(11, 'Guataqui'),
	(11, 'Guatavita'),
	(11, 'Guayabal De Siquima'),
	(11, 'Guayabetal'),
	(11, 'Gutierrez'),
	(11, 'Jerusalen'),
	(11, 'Junin'),
	(11, 'La Calera'),
	(11, 'La Mesa'),
	(11, 'La Palma'),
	(11, 'La Peña'),
	(11, 'La Vega'),
	(11, 'Lenguazaque'),
	(11, 'Macheta'),
	(11, 'Madrid'),
	(11, 'Manta'),
	(11, 'Medina'),
	(11, 'Mosquera'),
	(11, 'Nariño'),
	(11, 'Nemocon'),
	(11, 'Nilo'),
	(11, 'Nimaima'),
	(11, 'Nocaima'),
	(11, 'Venecia (Ospina Perez)'),
	(11, 'Pacho'),
	(11, 'Paime'),
	(11, 'Pandi'),
	(11, 'Paratebueno'),
	(11, 'Pasca'),
	(11, 'Puerto Salgar'),
	(11, 'Puli'),
	(11, 'Quebradanegra'),
	(11, 'Quetame'),
	(11, 'Quipile'),
	(11, 'Apulo (Rafael Reyes)'),
	(11, 'Ricaurte'),
	(11, 'San Antonio Del Tequendama'),
	(11, 'San Bernardo'),
	(11, 'San Cayetano'),
	(11, 'San Francisco'),
	(11, 'San Juan De Rioseco'),
	(11, 'Sasaima'),
	(11, 'Sesquile'),
	(11, 'Sibate'),
	(11, 'Silvania'),
	(11, 'Simijaca'),
	(11, 'Soacha'),
	(11, 'Sopo'),
	(11, 'Subachoque'),
	(11, 'Suesca'),
	(11, 'Supata'),
	(11, 'Susa'),
	(11, 'Sutatausa'),
	(11, 'Tabio'),
	(11, 'Tausa'),
	(11, 'Tena'),
	(11, 'Tenjo'),
	(11, 'Tibacuy'),
	(11, 'Tibirita'),
	(11, 'Tocaima'),
	(11, 'Tocancipa'),
	(11, 'Topaipi'),
	(11, 'Ubala'),
	(11, 'Ubaque'),
	(11, 'Ubate'),
	(11, 'Une'),
	(11, 'Utica'),
	(11, 'Vergara'),
	(11, 'Viani'),
	(11, 'Villagomez'),
	(11, 'Villapinzon'),
	(11, 'Villeta'),
	(11, 'Viota'),
	(11, 'Yacopi'),
	(11, 'Zipacon'),
	(11, 'Zipaquira'),
	(12, 'Quibdo (San Francisco De Quibdo)'),
	(12, 'Acandi'),
	(12, 'Alto Baudo (Pie De Pato)'),
	(12, 'Atrato'),
	(12, 'Bagado'),
	(12, 'Bahia Solano (Mutis)'),
	(12, 'Bajo Baudo (Pizarro)'),
	(12, 'Bojaya (Bellavista)'),
	(12, 'Canton De San Pablo (Managru)'),
	(12, 'Condoto'),
	(12, 'El Carmen De Atrato'),
	(12, 'Litoral Del Bajo San Juan (Santa Genoveva De Docordo)'),
	(12, 'Istmina'),
	(12, 'Jurado'),
	(12, 'Lloro'),
	(12, 'Medio Atrato'),
	(12, 'Medio Baudo'),
	(12, 'Novita'),
	(12, 'Nuqui'),
	(12, 'Rioquito'),
	(12, 'Riosucio'),
	(12, 'San Jose Del Palmar'),
	(12, 'Sipi'),
	(12, 'Tado'),
	(12, 'Unguia'),
	(12, 'Union Panamericana'),
	(13, 'Neiva'),
	(13, 'Acevedo'),
	(13, 'Agrado'),
	(13, 'Aipe'),
	(13, 'Algeciras'),
	(13, 'Altamira'),
	(13, 'Baraya'),
	(13, 'Campoalegre'),
	(13, 'Colombia'),
	(13, 'Elias'),
	(13, 'Garzon'),
	(13, 'Gigante'),
	(13, 'Guadalupe'),
	(13, 'Hobo'),
	(13, 'Iquira'),
	(13, 'Isnos (San Jose De Isnos)'),
	(13, 'La Argentina'),
	(13, 'La Plata'),
	(13, 'Nataga'),
	(13, 'Oporapa'),
	(13, 'Paicol'),
	(13, 'Palermo'),
	(13, 'Palestina'),
	(13, 'Pital'),
	(13, 'Pitalito'),
	(13, 'Rivera'),
	(13, 'Saladoblanco'),
	(13, 'San Agustin'),
	(13, 'Santa Maria'),
	(13, 'Suaza'),
	(13, 'Tarqui'),
	(13, 'Tesalia'),
	(13, 'Tello'),
	(13, 'Teruel'),
	(13, 'Timana'),
	(13, 'Villavieja'),
	(13, 'Yaguara'),
	(14, 'Riohacha'),
	(14, 'Barrancas'),
	(14, 'Dibulla'),
	(14, 'Distraccion'),
	(14, 'El Molino'),
	(14, 'Fonseca'),
	(14, 'Hatonuevo'),
	(14, 'La Jagua Del Pilar'),
	(14, 'Maicao'),
	(14, 'Manaure'),
	(14, 'San Juan Del Cesar'),
	(14, 'Uribia'),
	(14, 'Urumita'),
	(14, 'Villanueva'),
	(15, 'Santa Marta (Distrito Turistico Cultural E Historico De Santa Marta)'),
	(15, 'Algarrobo'),
	(15, 'Aracataca'),
	(15, 'Ariguani (El Dificil)'),
	(15, 'Cerro San Antonio'),
	(15, 'Chivolo'),
	(15, 'Cienaga'),
	(15, 'Concordia'),
	(15, 'El Banco'),
	(15, 'El Piñon'),
	(15, 'El Reten'),
	(15, 'Fundacion'),
	(15, 'Guamal'),
	(15, 'Pedraza'),
	(15, 'Pijiño Del Carmen (Pijiño)'),
	(15, 'Pivijay'),
	(15, 'Plato'),
	(15, 'Puebloviejo'),
	(15, 'Remolino'),
	(15, 'Sabanas De San Angel'),
	(15, 'Salamina'),
	(15, 'San Sebastian De Buenavista'),
	(15, 'San Zenon'),
	(15, 'Santa Ana'),
	(15, 'Sitionuevo'),
	(15, 'Tenerife'),
	(16, 'Villavicencio'),
	(16, 'Acacias'),
	(16, 'Barranca De Upia'),
	(16, 'Cabuyaro'),
	(16, 'Castilla La Nueva'),
	(16, 'San Luis De Cubarral'),
	(16, 'Cumaral'),
	(16, 'El Calvario'),
	(16, 'El Castillo'),
	(16, 'El Dorado'),
	(16, 'Fuente De Oro'),
	(16, 'Granada'),
	(16, 'Guamal'),
	(16, 'Mapiripan'),
	(16, 'Mesetas'),
	(16, 'La Macarena'),
	(16, 'La Uribe'),
	(16, 'Lejanias'),
	(16, 'Puerto Concordia'),
	(16, 'Puerto Gaitan'),
	(16, 'Puerto Lopez'),
	(16, 'Puerto Lleras'),
	(16, 'Puerto Rico'),
	(16, 'Restrepo'),
	(16, 'San Carlos De Guaroa'),
	(16, 'San Juan De Arama'),
	(16, 'San Juanito'),
	(16, 'San Martin'),
	(16, 'Vistahermosa'),
	(17, 'Pasto (San Juan De Pasto)'),
	(17, 'Alban (San Jose)'),
	(17, 'Aldana'),
	(17, 'Ancuya'),
	(17, 'Arboleda (Berruecos)'),
	(17, 'Barbacoas'),
	(17, 'Belen'),
	(17, 'Buesaco'),
	(17, 'Colon (Genova)'),
	(17, 'Consaca'),
	(17, 'Contadero'),
	(17, 'Cordoba'),
	(17, 'Cuaspud (Carlosama)'),
	(17, 'Cumbal'),
	(17, 'Cumbitara'),
	(17, 'Chachagui'),
	(17, 'El Charco'),
	(17, 'El Peñol'),
	(17, 'El Rosario'),
	(17, 'El Tablon'),
	(17, 'El Tambo'),
	(17, 'Funes'),
	(17, 'Guachucal'),
	(17, 'Guaitarilla'),
	(17, 'Gualmatan'),
	(17, 'Iles'),
	(17, 'Imues'),
	(17, 'Ipiales'),
	(17, 'La Cruz'),
	(17, 'La Florida'),
	(17, 'La Llanada'),
	(17, 'La Tola'),
	(17, 'La Union'),
	(17, 'Leiva'),
	(17, 'Linares'),
	(17, 'Los Andes (Sotomayor)'),
	(17, 'Magui (Payan)'),
	(17, 'Mallama (Piedrancha)'),
	(17, 'Mosquera'),
	(17, 'Olaya Herrera (Bocas De Satinga)'),
	(17, 'Ospina'),
	(17, 'Francisco Pizarro (Salahonda)'),
	(17, 'Policarpa'),
	(17, 'Potosi'),
	(17, 'Providencia'),
	(17, 'Puerres'),
	(17, 'Pupiales'),
	(17, 'Ricaurte'),
	(17, 'Roberto Payan (San Jose)'),
	(17, 'Samaniego'),
	(17, 'Sandona'),
	(17, 'San Bernardo'),
	(17, 'San Lorenzo'),
	(17, 'San Pablo'),
	(17, 'San Pedro De Cartago'),
	(17, 'Santa Barbara (Iscuande)'),
	(17, 'Santa Cruz (Guachaves)'),
	(17, 'Sapuyes'),
	(17, 'Taminango'),
	(17, 'Tangua'),
	(17, 'Tumaco'),
	(17, 'Tuquerres'),
	(17, 'Yacuanquer'),
	(18, 'Cucuta'),
	(18, 'Abrego'),
	(18, 'Arboledas'),
	(18, 'Bochalema'),
	(18, 'Bucarasica'),
	(18, 'Cacota'),
	(18, 'Cachira'),
	(18, 'Chinacota'),
	(18, 'Chitaga'),
	(18, 'Convencion'),
	(18, 'Cucutilla'),
	(18, 'Durania'),
	(18, 'El Carmen'),
	(18, 'El Tarra'),
	(18, 'El Zulia'),
	(18, 'Gramalote'),
	(18, 'Hacari'),
	(18, 'Herran'),
	(18, 'Labateca'),
	(18, 'La Esperanza'),
	(18, 'La Playa'),
	(18, 'Los Patios'),
	(18, 'Lourdes'),
	(18, 'Mutiscua'),
	(18, 'Ocaña'),
	(18, 'Pamplona'),
	(18, 'Pamplonita'),
	(18, 'Puerto Santander'),
	(18, 'Ragonvalia'),
	(18, 'Salazar'),
	(18, 'San Calixto'),
	(18, 'San Cayetano'),
	(18, 'Santiago'),
	(18, 'Sardinata'),
	(18, 'Silos'),
	(18, 'Teorama'),
	(18, 'Tibu'),
	(18, 'Toledo'),
	(18, 'Villacaro'),
	(18, 'Villa Del Rosario'),
	(19, 'Armenia'),
	(19, 'Buenavista'),
	(19, 'Calarca'),
	(19, 'Circasia'),
	(19, 'Cordoba'),
	(19, 'Filandia'),
	(19, 'Genova'),
	(19, 'La Tebaida'),
	(19, 'Montenegro'),
	(19, 'Pijao'),
	(19, 'Quimbaya'),
	(19, 'Salento'),
	(20, 'Pereira'),
	(20, 'Apia'),
	(20, 'Balboa'),
	(20, 'Belen De Umbria'),
	(20, 'Dos Quebradas'),
	(20, 'Guatica'),
	(20, 'La Celia'),
	(20, 'La Virginia'),
	(20, 'Marsella'),
	(20, 'Mistrato'),
	(20, 'Pueblo Rico'),
	(20, 'Quinchia'),
	(20, 'Santa Rosa De Cabal'),
	(20, 'Santuario'),
	(21, 'Bucaramanga'),
	(21, 'Aguada'),
	(21, 'Albania'),
	(21, 'Aratoca'),
	(21, 'Barbosa'),
	(21, 'Barichara'),
	(21, 'Barrancabermeja'),
	(21, 'Betulia'),
	(21, 'Bolivar'),
	(21, 'Cabrera'),
	(21, 'California'),
	(21, 'Capitanejo'),
	(21, 'Carcasi'),
	(21, 'Cepita'),
	(21, 'Cerrito'),
	(21, 'Charala'),
	(21, 'Charta'),
	(21, 'Chima'),
	(21, 'Chipata'),
	(21, 'Cimitarra'),
	(21, 'Concepcion'),
	(21, 'Confines'),
	(21, 'Contratacion'),
	(21, 'Coromoro'),
	(21, 'Curiti'),
	(21, 'El Carmen De Chucury'),
	(21, 'El Guacamayo'),
	(21, 'El Peñon'),
	(21, 'El Playon'),
	(21, 'Encino'),
	(21, 'Enciso'),
	(21, 'Florian'),
	(21, 'Floridablanca'),
	(21, 'Galan'),
	(21, 'Gambita'),
	(21, 'Giron'),
	(21, 'Guaca'),
	(21, 'Guadalupe'),
	(21, 'Guapota'),
	(21, 'Guavata'),
	(21, 'Guepsa'),
	(21, 'Hato'),
	(21, 'Jesus Maria'),
	(21, 'Jordan'),
	(21, 'La Belleza'),
	(21, 'Landazuri'),
	(21, 'La Paz'),
	(21, 'Lebrija'),
	(21, 'Los Santos'),
	(21, 'Macaravita'),
	(21, 'Malaga'),
	(21, 'Matanza'),
	(21, 'Mogotes'),
	(21, 'Molagavita'),
	(21, 'Ocamonte'),
	(21, 'Oiba'),
	(21, 'Onzaga'),
	(21, 'Palmar'),
	(21, 'Palmas Del Socorro'),
	(21, 'Paramo'),
	(21, 'Piedecuesta'),
	(21, 'Pinchote'),
	(21, 'Puente Nacional'),
	(21, 'Puerto Parra'),
	(21, 'Puerto Wilches'),
	(21, 'Rionegro'),
	(21, 'Sabana De Torres'),
	(21, 'San Andres'),
	(21, 'San Benito'),
	(21, 'San Gil'),
	(21, 'San Joaquin'),
	(21, 'San Jose De Miranda'),
	(21, 'San Miguel'),
	(21, 'San Vicente De Chucuri'),
	(21, 'Santa Barbara'),
	(21, 'Santa Helena Del Opon'),
	(21, 'Simacota'),
	(21, 'Socorro'),
	(21, 'Suaita'),
	(21, 'Sucre'),
	(21, 'Surata'),
	(21, 'Tona'),
	(21, 'Valle San Jose'),
	(21, 'Velez'),
	(21, 'Vetas'),
	(21, 'Villanueva'),
	(21, 'Zapatoca'),
	(22, 'Sincelejo'),
	(22, 'Buenavista'),
	(22, 'Caimito'),
	(22, 'Coloso (Ricaurte)'),
	(22, 'Corozal'),
	(22, 'Chalan'),
	(22, 'Galeras (Nueva Granada)'),
	(22, 'Guaranda'),
	(22, 'La Union'),
	(22, 'Los Palmitos'),
	(22, 'Majagual'),
	(22, 'Morroa'),
	(22, 'Ovejas'),
	(22, 'Palmito'),
	(22, 'Sampues'),
	(22, 'San Benito Abad'),
	(22, 'San Juan De Betulia'),
	(22, 'San Marcos'),
	(22, 'San Onofre'),
	(22, 'San Pedro'),
	(22, 'Since'),
	(22, 'Sucre'),
	(22, 'Tolu'),
	(22, 'Toluviejo'),
	(23, 'Ibague'),
	(23, 'Alpujarra'),
	(23, 'Alvarado'),
	(23, 'Ambalema'),
	(23, 'Anzoategui'),
	(23, 'Armero (Guayabal)'),
	(23, 'Ataco'),
	(23, 'Cajamarca'),
	(23, 'Carmen Apicala'),
	(23, 'Casabianca'),
	(23, 'Chaparral'),
	(23, 'Coello'),
	(23, 'Coyaima'),
	(23, 'Cunday'),
	(23, 'Dolores'),
	(23, 'Espinal'),
	(23, 'Falan'),
	(23, 'Flandes'),
	(23, 'Fresno'),
	(23, 'Guamo'),
	(23, 'Herveo'),
	(23, 'Honda'),
	(23, 'Icononzo'),
	(23, 'Lerida'),
	(23, 'Libano'),
	(23, 'Mariquita'),
	(23, 'Melgar'),
	(23, 'Murillo'),
	(23, 'Natagaima'),
	(23, 'Ortega'),
	(23, 'Palocabildo'),
	(23, 'Piedras'),
	(23, 'Planadas'),
	(23, 'Prado'),
	(23, 'Purificacion'),
	(23, 'Rioblanco'),
	(23, 'Roncesvalles'),
	(23, 'Rovira'),
	(23, 'Saldaña'),
	(23, 'San Antonio'),
	(23, 'San Luis'),
	(23, 'Santa Isabel'),
	(23, 'Suarez'),
	(23, 'Valle De San Juan'),
	(23, 'Venadillo'),
	(23, 'Villahermosa'),
	(23, 'Villarrica'),
	(24, 'Cali (Santiago De Cali)'),
	(24, 'Alcala'),
	(24, 'Andalucia'),
	(24, 'Ansermanuevo'),
	(24, 'Argelia'),
	(24, 'Bolivar'),
	(24, 'Buenaventura'),
	(24, 'Buga'),
	(24, 'Bugalagrande'),
	(24, 'Caicedonia'),
	(24, 'Calima (Darien)'),
	(24, 'Candelaria'),
	(24, 'Cartago'),
	(24, 'Dagua'),
	(24, 'El Aguila'),
	(24, 'El Cairo'),
	(24, 'El Cerrito'),
	(24, 'El Dovio'),
	(24, 'Florida'),
	(24, 'Ginebra'),
	(24, 'Guacari'),
	(24, 'Jamundi'),
	(24, 'La Cumbre'),
	(24, 'La Union'),
	(24, 'La Victoria'),
	(24, 'Obando'),
	(24, 'Palmira'),
	(24, 'Pradera'),
	(24, 'Restrepo'),
	(24, 'Riofrio'),
	(24, 'Roldanillo'),
	(24, 'San Pedro'),
	(24, 'Sevilla'),
	(24, 'Toro'),
	(24, 'Trujillo'),
	(24, 'Tulua'),
	(24, 'Ulloa'),
	(24, 'Versalles'),
	(24, 'Vijes'),
	(24, 'Yotoco'),
	(24, 'Yumbo'),
	(24, 'Zarzal'),
	(25, 'Arauca'),
	(25, 'Arauquita'),
	(25, 'Cravo Norte'),
	(25, 'Fortul'),
	(25, 'Puerto Rondon'),
	(25, 'Saravena'),
	(25, 'Tame'),
	(26, 'Yopal'),
	(26, 'Aguazul'),
	(26, 'Chameza'),
	(26, 'Hato Corozal'),
	(26, 'La Salina'),
	(26, 'Mani'),
	(26, 'Monterrey'),
	(26, 'Nunchia'),
	(26, 'Orocue'),
	(26, 'Paz De Ariporo'),
	(26, 'Pore'),
	(26, 'Recetor'),
	(26, 'Sabanalarga'),
	(26, 'Sacama'),
	(26, 'San Luis De Palenque'),
	(26, 'Tamara'),
	(26, 'Tauramena'),
	(26, 'Trinidad'),
	(26, 'Villanueva'),
	(27, 'Mocoa'),
	(27, 'Colon'),
	(27, 'Orito'),
	(27, 'Puerto Asis'),
	(27, 'Puerto Caicedo'),
	(27, 'Puerto Guzman'),
	(27, 'Puerto Leguizamo'),
	(27, 'Sibundoy'),
	(27, 'San Francisco'),
	(27, 'San Miguel (La Dorada)'),
	(27, 'Santiago'),
	(27, 'La Hormiga (Valle Del Guamuez)'),
	(27, 'Villagarzon'),
	(28, 'San Andres'),
	(28, 'Providencia'),
	(29, 'Leticia'),
	(29, 'El Encanto'),
	(29, 'La Chorrera'),
	(29, 'La Pedrera'),
	(29, 'La Victoria'),
	(29, 'Miriti-Parana'),
	(29, 'Puerto Alegria'),
	(29, 'Puerto Arica'),
	(29, 'Puerto Nariño'),
	(29, 'Puerto Santander'),
	(29, 'Tarapaca'),
	(30, 'Puerto Inirida'),
	(30, 'Barranco Minas'),
	(30, 'San Felipe'),
	(30, 'Puerto Colombia'),
	(30, 'La Guadalupe'),
	(30, 'Cacahual'),
	(30, 'Pana Pana (Campo Alegre)'),
	(30, 'Morichal (Morichal Nuevo)'),
	(31, 'San Jose Del Guaviare'),
	(31, 'Calamar'),
	(31, 'El Retorno'),
	(31, 'Miraflores'),
	(32, 'Mitu'),
	(32, 'Caruru'),
	(32, 'Pacoa'),
	(32, 'Taraira'),
	(32, 'Papunaua (Morichal)'),
	(32, 'Yavarate'),
	(33, 'Puerto Carreño'),
	(33, 'La Primavera'),
	(33, 'Santa Rita'),
	(33, 'Santa Rosalia'),
	(33, 'San Jose De Ocune'),
	(33, 'Cumaribo');